# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

# Admin.create(email: "admin@admin.com", password: "123456")
# Admin.create(email: "bruno@admin.com", password: "123qwe")
puts "admin created"

Product.create(title: "Chuteira Predator Freak.3", description: "Chuteira Sem Cadarços Predator Freak.3 Campo", value: 349, image: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/e71c01aaf40046f4919aac7700d49196_9366/Chuteira_Sem_Cadarcos_Predator_Freak.3_Campo_Preto_FW7529_01_standard.jpg")
Product.create(title: "Tênis Deportivo Indoor", description: "Controle no futebol de quadra. Os jogos recreativos pedem agilidade. Este tênis de futebol indoor adidas ajuda você a assumir o controle. O cabedal de suporte prende o tênis ao tornozelo. Cadarços assimétricos fornecem uma zona de impacto ampla, com costuras de controle que ajudam a reter a bola nos pés.", value: 279, image:"https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/b88c12b0ed8c4883ba3facb800911525_9366/Tenis_Deportivo_Indoor_Preto_FY7621_01_standard.jpg")
Product.create(title: "Minibola Conext 21", description: "O mundo gira ao ritmo do futebol-arte. A minibola Conext 21 adidas exibe um design vibrante inspirado no movimento. Seus painéis interligados representam a unidade das seis federações continentais de futebol. Por baixo da superfície laminada, o núcleo de espuma significa que você não precisa de uma bomba para manter esta pequena bola rolando.", value: 89, image: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/3b7341a09fc940308c22ac7e01293638_9366/Minibola_Conext_21_Branco_GK3487_01_standard.jpg")
Product.create(title: "Bola Basquete All Court 2.0", description: "Prepare-se para o jogo com esta bola de basquete adidas All Court 2.0. Seu tamanho oficial e acabamento sintético dão um toque autêntico enquanto você arma a jogada. Com estrutura durável, ela foi desenvolvida para jogo em múltiplas superfícies, do asfalto ao piso de madeira dura da quadra.", value: 250, image: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/8d1778943c7644a9bd01abfb0127cc46_9366/Bola_Basquete_All_Court_2.0_Preto_GL3946_01_standard.jpg")
Product.create(title: "Tênis Run Falcon 2.0", description: "Prepare-se para correr no parque com este tênis adidas, seguido de um café com os amigos. Com cabedal em mesh para maior respirabilidade, ele proporciona conforto o dia todo. O solado de borracha durável oferece uma base sólida, não importa quão cheia esteja a sua agenda.", value: 350, image: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/9e3fc68545aa4d6698ecad6a00c468e1_9366/Tenis_Run_Falcon_2.0_Rosa_GX8248_01_standard.jpg")
Product.create(title: "Camiseta Parley Adizero Running", description: "Não importa se você gosta de correr só pela sensação de liberdade ou para cruzar a linha de chegada em primeiro lugar. Com esta camiseta de corrida adidas, você também estará correndo pelos oceanos. ", value: 300, image:"https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/9fd33793ccf848dabd03adf0009be9aa_9366/Camiseta_Parley_Adizero_Running_Vermelho_HG1220_01_laydown.jpg")
Product.create(title: "Chuteira Nike Phantom GT Academy Unissex", description: "O design da Nike Phantom GT Academy Dynamic Fit TF foi baseado em dados e criado para ataques precisos. A textura inovadora na parte de cima e a tração focada na parte de baixo proporcionam mais controle durante o jogo. A boca elástica cria uma sensação de segurança para que você possa se concentrar em seu desempenho.", value: 499, image: "https://images.lojanike.com.br/500x500/produto/chuteira-nike-phantom-gt-academy-unissex-CW6666-303-1.jpg")
Product.create(title: "Bola Nike Premier League Flight", description: "Aperfeiçoada ao longo de 8 anos e 1.700 horas de testes, a bola de futebol Premier League Flight é uma revolução em consistência de voo. Sulcos moldados e uma textura aderente reduzem movimentos inesperados durante o voo para que você possa posicionar a bola com mais precisão.", value: 659, image: "https://images.lojanike.com.br/860x860/produto/bola-nike-premier-league-flight-DC2209-710-1-11635943016.jpg")
Product.create(title: "Bolsa Nike Gym Club Infantil", description: "A sacola Nike Gym Club te prepara para o treino, o jogo ou sua próxima aventura. Esta sacola tem um compartimento principal com zíper inteiriço e bolsos internos para manter a organização. Carregue-a com a mão ou ao redor dos ombros para que seu equipamento esteja sempre próximo.", value: 199, image: "https://images.lojanike.com.br/500x500/produto/bolsa-nike-gym-club-infantil-BA5567-010-1-11626441315.jpg")
Product.create(title: "Mountain Bike South Bike Schon - Aro 29 - Freio a disco Mecânico - Adulto", description: "Com geometria moderna e quadro leve em alumínio 6061, a Mountain Bike South Bike Schon é um excelente custo-benefício para se aventurar em trilhas leves ou circuitos urbanos. ", value: 1599, image: "https://imgcentauro-a.akamaihd.net/900x900/96176334/mountain-bike-south-bike-schon-aro-29-freio-a-disco-mecanico-adulto-img.jpg")
Product.create(title: "Camisa do Atlético-MG I 21 Lecoq Sportif- Masculina", description: "Camisa do maior de minas xD", value: 279, image: "https://imgcentauro-a.akamaihd.net/900x900/96371831/camisa-do-atletico-mg-i-21-lecoq-sportif-masculina-img.jpg")
Product.create(title: "Skate Street X7 Caver Style", description: " Realize manobras radicais com o skate Caver Style, seus materiais tem a qualidade necessária para acompanhar seu ânimo e seus desafios. Possui 7 lâminas, amortecedores de 85A, rolamento de 608 ZZ e peso máximo suportado de 90 kg. Não perca mais tempo e compre um skate com o padrão X7 agora mesmo.", value: 189, image: "https://imgcentauro-a.akamaihd.net/900x900/8922494J/skate-street-x7-caver-style-img.jpg")
Product.create(title: "Raquete de Beach Tennis Vammo Next Gen P - Adulto", description: "A qualidade Vammo em todos os detalhes com a raquete de beach tennis. Realize suas partidas com muito mais estilo e mais conforto com o alto padrão Vammo. Possui 48 furos bem distribuídos em sua superfície áspera. A matéria prima é em EVA e fibra de vidro, além de conter uma capa para guardar sua raquete. Confira as tecnologias na raquete Next Gen P: ", value: 649, image: "https://imgcentauro-a.akamaihd.net/900x900/969124LZ/raquete-de-beach-tennis-vammo-next-gen-p-adulto-img.jpg")
Product.create(title: "Raquete de Tênis Wilson Pro Staff Precision XL 110", description: "Para melhor performance dentro das quadras, essa Raquete de Tênis Wilson é a pedida certa. Encordoada e com alumínio em sua composição oferece leveza e estabilidade. Além disso, a Raquete Pro Staff Precision XL 110 possui empunhadura emborrachada para maior aderência, potência e controle durante seus treinos ou jogadas. Compre a sua!", value: 259, image: "https://imgcentauro-a.akamaihd.net/900x900/94881306/raquete-de-tenis-wilson-pro-staff-precision-xl-110-img.jpg")
Product.create(title: "Capacete para Bike Absolute Nero Azul e Branco G - Adulto", description: "Um acessório indispensável para usar durante os passeios de bike é o Capacete para Bike Absolute Nero Azul e Branco G. O capacete é em material poliamida e polímero termoplástico, além de forro levemente acolchoado que remove facilitando a limpeza.", value: 199, image: "https://imgcentauro-a.akamaihd.net/900x900/9707972R/capacete-para-bike-absolute-nero-azul-e-branco-g-adulto-img.jpg")
Product.create(title: "Squeeze Oxer Acqua - 800ml", description: "Hidratar-se diariamente é fundamental para repor os nutrientes perdidos e aumentar o desempenho e bem-estar. Livre de BPA, o o Squeeze Oxer Acqua é desenvolvido em material leve e resistente com marcadores que facilitam a visibilidade do líquido ingerido. Sua tampa é rosqueável com tira emborrachada para aderência e firmeza na abertura com bico dosador que ajuda a evitar vazamentos. Já a alça embutida facilita o transporte para maior praticidade.", value: 26, image: "https://imgcentauro-a.akamaihd.net/900x900/922258EZ/squeeze-oxer-acqua-800ml-img.jpg")
Product.create(title: "Óculos de Natação Oxer Max - Adulto", description: "Com design ergonômico facilitado pela maleabilidade do silicone, os Óculos de Natação Oxer oferecem ajuste regulável e personalizado por presilha traseira. Já as lentes desses óculos de natação são em policarbonato com Proteção UV e tratamento antiembaçante para você superar as habilidades aquáticas com conforto e muito desempenho.", value: 34, image: "https://imgcentauro-a.akamaihd.net/900x900/94263832/oculos-de-natacao-oxer-max-adulto-img.jpg")
Product.create(title: "Meião Puma Liga Socks Core - Adulto", description: "A opção perfeita para o bate-bola, esse Meião Puma foi confeccionado com materiais leves e macios que garantem extremo conforto em todas as partidas. Com sola macia e atoalhada, o meião apresenta punho elástico e detalhe canelado no tornozelo que ajuda a evitar seu deslocamento, ideal para excelente adaptação aos pés dos craques. ", value: 19, image: "https://imgcentauro-a.akamaihd.net/900x900/92575131/meiao-puma-liga-socks-core-adulto-img.jpg")
Product.create(title: "Rash Guard Venum Basic - Masculina", description: "A Nova Camisa RASHGUARD VENUM BASIC faz seus músculos ficarem aquecidos durante toda a prática esportiva, além de controlar o suor excessivo. As costuras da Nova Camisa RASHGUARD VENUM BASIC são posicionadas de forma anatômica e confortável, jamais vão assar ou impedir sua movimentação.", value: 158, image: "https://imgcentauro-a.akamaihd.net/900x900/M0BUAY02/rash-guard-venum-basic-masculina-img.jpg")
Product.create(title: "Caiaque Hidro2 Tuna STD Areia", description: "Um novo conceito de caiaque para pesca que recebe o nome de um dos peixes mais conhecidos do mundo da pesca: o atum!", value: 2099, image: "https://imgcentauro-a.akamaihd.net/900x900/M0N8WL12/caiaque-hidro2-tuna-std-areia-img.jpg")
Product.create(title: "Colchonete de Academia Profissional Oxer D-40", description: "Fabricado em material resistente e enchimento em espuma, esse Colchonete Oxer é uma ótima opção para você realizar as mais variadas atividades com maior segurança. Prático e leve, o Colchonete de Academia Profissional é dobrável e fácil de transportar", value: 69, image: "https://imgcentauro-a.akamaihd.net/900x900/78727102/colchonete-de-academia-profissional-oxer-d-40-102-x-50-x-3-cm-img.jpg")
Product.create(title: "Corda de Pular com Rolamento Ajustável Oxer - 2,75 metros", description: "Indicada para todos os níveis de atletas, a Corda de Pular com Rolamento Ajustável Oxer é um excelente e econômico custo-benefício para a melhora do condicionamento físico. Seu comprimento é longo em 2,75 com a prática possibilidade de regulagem para ajuste de acordo com a altura do usuário", value: 19, image: "https://imgcentauro-a.akamaihd.net/900x900/94272800/corda-de-pular-com-rolamento-ajustavel-oxer-2-75-metros-img.jpg")
Product.create(title: "Bola de Futebol Americano Wilson NFL Super Grip", description: "A bola de futebol americano Wilson NFL Super Grip Cover é confeccionada em microfibra de PU. Costurada à máquina, conta com o sistema Super Grip Cover que promove maior grip e controle. ", value: 170, image: "https://imgcentauro-a.akamaihd.net/900x900/M0IC8J15/bola-de-futebol-americano-wilson-nfl-super-grip-img.jpg")
Product.create(title: "Bola Penalty Futebol Americano VIII", description: "A Bola Penalty Futebol Americano VIII tem ótima durabilidade e resistência, conta com laminado em PU e textura que ajuda a aderência durante as jogadas.", value: 168, image: "https://imgcentauro-a.akamaihd.net/900x900/M0HBA12Y/bola-penalty-futebol-americano-viii-img.jpg")


puts "product created"